version: "3.9"
# Explicação
# 1. Isolamento de Redes:
# Cada banco de dados está conectado a duas redes:
# - uma rede com sua aplicação correspondente (db1_net, db2_net, db3_net)
# - uma sub-rede exclusiva para backups (backup1_net, backup2_net, backup3_net)
# isso garante que os backups não tenham visibilidade para outros serviços
# 2. Contêineres de Backup:
# Contêineres de Backup:
# - Contêineres baseados na imagem jadilsonpaiva/full são consifgurados em suas respectivas sub-redes
#- Esses contêineres só podem comunicar-se com o banco de dados na mesma sub-rede
services:
  # Banco de Dados 1
  db1:
    image: mysql:5.7
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    networks:
      db1_net:
        ipv4_address: 10.10.11.2
      backup1_net:
        ipv4_address: 10.10.21.2

  # Contêiner de Backup 1
  backup1:
    image: jadilsonpaiva/full
    container_name: backup1
    networks:
      backup1_net:
        ipv4_address: 10.10.21.3

  # Banco de Dados 2
  db2:
    image: mysql:5.7
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword2
      MYSQL_DATABASE: db2
      MYSQL_USER: user2
      MYSQL_PASSWORD: password2
    networks:
      db2_net:
        ipv4_address: 10.10.12.2
      backup2_net:
        ipv4_address: 10.10.22.2

  # Contêiner de Backup 2
  backup2:
    image: jadilsonpaiva/full
    container_name: backup2
    networks:
      backup2_net:
        ipv4_address: 10.10.22.3

  # Banco de Dados 3
  db3:
    image: mysql:5.7
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword3
      MYSQL_DATABASE: db3
      MYSQL_USER: user3
      MYSQL_PASSWORD: password3
    networks:
      db3_net:
        ipv4_address: 10.10.13.2
      backup3_net:
        ipv4_address: 10.10.23.2

  # Contêiner de Backup 3
  backup3:
    image: jadilsonpaiva/full
    container_name: backup3
    networks:
      backup3_net:
        ipv4_address: 10.10.23.3

networks:
  # Redes existentes para bancos de dados
  db1_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24

  db2_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.12.0/24

  db3_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.13.0/24

  # Sub-redes para backups
  backup1_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.21.0/24

  backup2_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.22.0/24

  backup3_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.23.0/24
