version: "3.9"

services:
  app1:
    build:
      context: ./app1
    container_name: app1
    networks:
      app1_net:
        ipv4_address: 10.10.10.2

  app1_db:
    image: postgres:alpine
    container_name: app1_db
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    networks:
      app1_net:
        ipv4_address: 10.10.10.3

  app2:
    build:
      context: ./app2
    container_name: app2
    networks:
      app2_net:
        ipv4_address: 10.10.10.66

  app2_db:
    image: postgres:alpine
    container_name: app2_db
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    networks:
      app2_net:
        ipv4_address: 10.10.10.67

  app3:
    build:
      context: ./app3
    container_name: app3
    networks:
      app3_net:
        ipv4_address: 10.10.10.130

  app3_db:
    image: postgres:alpine
    container_name: app3_db
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: db3
    networks:
      app3_net:
        ipv4_address: 10.10.10.131

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      proxy_net:
        ipv4_address: 10.10.10.194
      app1_net:
      app2_net:
      app3_net:

networks:
  app1_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/26

  app2_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.64/26

  app3_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.128/26

  proxy_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.192/26
